### ISSUE TITLE
Yeti Tooth using stab attack instead of defensive parry

### ISSUE THREAD

**Issue by Chanocraft** [daleao/modular-overhaul#75]
While playing the game normally, I noticed that my Yeti Tooth has started to use the stabbing attack, when it normally would use the defensive parry. since I don't use the defensive parry on a regular basis, I do not know exactly when this change occurred. My main theory at the moment is the change might've occurred after I lost the Yeti Tooth when dying in the mines, and paid the adventurer's guild to retrieve it for me. some additional info in case it helps: I have a rapier (stabbing sword) in my last slot, because I've discovered the stabbing is a good boost to general movement early game. The change persists between days and upon restarting the game.

**Comment by daleao** [comment]
I've no idea why that would be happening since the mod revalidates all weapons on load.
But in any case, if you select the Yeti Tooth and type `cmbt revalidate` in the console, that should fix it.

**Comment by Chanocraft** [comment]
after revalidating the yeti tooth the issue still persists, even after a relaunch

**Comment by daleao** [comment]
Issue will be fixed on the next version.
